# Generated by Django 4.2.1 on 2023-05-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('SKU', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('quantity', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=250)),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.category')),
            ],
        ),
    ]
