# Generated by Django 4.2.1 on 2023-05-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId', models.CharField(max_length=250)),
                ('client_name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('bike_name', models.CharField(max_length=250)),
                ('service_type', models.CharField(max_length=250)),
                ('first_service', models.DateField()),
                ('second_service', models.DateField()),
                ('third_service', models.DateField()),
                ('fourth_service', models.DateField()),
                ('fifth_service', models.DateField()),
                ('sixth_service', models.DateField()),
                ('seventh_service', models.DateField()),
                ('eighth_service', models.DateField()),
            ],
        ),
    ]
